### PR TITLE
Xiaomi MJSXJ03HL MMC & MAC fix

### PR DESCRIPTION
**Pull request by Andrik45719**
1. gpio_mmc_power is defined otherwise **u-boot can't load autoupdate-full.bin** if env broken/clean.
2. Disable MAC autogenerating.
3. gpio_button defined.

### CODE REVIEW

**Comment by themactep** [comment]
we do not define per-camera settings in uboot. the bootloader is camera-agnostic. settings are populated on first boot, and on the next boot you have gpio_button et al, and access to autoupdate files.

**Comment by gtxaspec** [comment]
@Andrik45719 is there any reason you disabled mac generation? we generate MAC addresses for both ethernet and wireless based on the serial number of the SoC, so it never changes.

**Comment by Andrik45719** [comment]
> @Andrik45719 is there any reason you disabled mac generation? we generate MAC addresses for both ethernet and wireless based on the serial number of the SoC, so it never changes.

To use Xiaomi MAC flashed in camera.

**Comment by themactep** [comment]
You can restore the vendor provided mac address back if you wish, but that is a blocking change for thingino as in the pr. We generate a permanent mac address for each device based on its hardware id.

**Comment by gtxaspec** [comment]
the reason we generate mac address based on SoC serial number, some vendors do not set the mac address in the efuse on realtek/ssv chipsets, so you get a random mac on every power-up.  setting it based on soc serial number resolves this issue.

**Comment by gtxaspec** [comment]
@Andrik45719 u-boot has been updated to allow buildroot to embed the env configuration into the compiled binary.  This means GPIOs configured in the uenv.txt environment file are now embedded into uboot.  So the MMC should work fine on initial installation now.

**Comment by Andrik45719** [comment]
> @Andrik45719 u-boot has been updated to allow buildroot to embed the env configuration into the compiled binary. This means GPIOs configured in the uenv.txt environment file are now embedded into uboot. So the MMC should work fine on initial installation now on the MJSXJ03HL. If you have time, please test it, the changes in the PR should no longer be needed.

Works as expected after erasing ENV gpio_mmc_power: 54o is set and SD card is detected

**Pull request closed without merging**
